# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
# see https://chromium.googlesource.com/external/github.com/flutter/flutter/+/v0.5.5/analysis_options.yaml
include: package:pedantic/analysis_options.1.9.0.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

linter:
  rules :
    always_specify_types
    always_declare_return_types:true


analyzer:
#   exclude:
#     - path/to/excluded/files/**

