name: boond_wf
description: A GUI to read email and feed Boond Candidate database

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
author: patrouil
version: 0.0.4

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
#


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Model Vue Controler Pattern
  flutter_bloc: ^6.0.0
  # Notification
  flutter_styled_toast: ^1.4.0
  url_launcher: ^5.0.0
  flutter_markdown: ^0.5.0
  # settings user interface
  #shared_preferences_web: ^0.1.2+4
  #shared_preferences: ^0.5.6+3
  shared_preferences_settings: ^1.2.0
  global_configuration: ^1.0.0
  # to show  html message body
  # flutter_html : ^1.0.0
  #flutter_widget_from_html: ^0.4.1
  # more icons
  line_awesome_icons: ^1.0.4
  # mail  client
  #imap_client: ^0.2.9
  # for google mail
  googleapis: ">=0.55.0  <1.0.0"
  googleapis_auth: ^0.2.12
  _discoveryapis_commons: ^0.2.0
  #
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # local boond manager
  jaguar_jwt: ^2.1.6
  #
  boond_api :
    #path : ../boond_api
    git:
      url : https://github.com/patrouil/boond_api.git
      ref : 0.0.1
  # utilities at the end due to namespace collision.
  logging: ^0.11.4
  quiver: ^2.1.3
  intl: ^0.16.1
  http: ^0.12.1
  html: ^0.14.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  #build_test: ^0.10.2
  build_web_compilers: ^2.10.0

  pedantic: ^1.9.0  # control coding style. see analysis_options.yaml
#
# flutter run -d web-server  --web-port 7878
#
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - README.md
    - assets/boond-icon.png
    - assets/favicon.png
    - assets/cfg/sample-settings.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
